<?php if ($this->pageCount) : ?>
    <nav>
        <ul class="pagination justify-content-center">
            <!-- Previous page link -->
            <?php if (isset($this->previous)) : ?>
                <li class="page-item">
                    <a href="<?= $this->url($this->route, [], ['query' => ['page' => $this->previous]]) ?>" class="page-link" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                        <span class="sr-only">Previous</span>
                    </a>
                </li>
            <?php else : ?>
                <li class="page-item disabled">
                    <span class="page-link">Previous</span>
                </li>
            <?php endif ?>

            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page) : ?>
                <?php if ($page !== $this->current) : ?>
                    <li class="page-item">
                        <a href="<?= $this->url($this->route, [], ['query' => ['page' => $page]]) ?>" class="page-link">
                            <?= $page ?>
                        </a>
                    </li>
                <?php else : ?>
                    <li class="page-item active" aria-current="page">
                        <span class="page-link"><?= $page ?></span>
                    </li>
                <?php endif ?>
            <?php endforeach ?>

            <!-- Next page link -->
            <?php if (isset($this->next)) : ?>
                <li class="page-item">
                    <a href="<?= $this->url($this->route, [], ['query' => ['page' => $this->next]]) ?>" class="page-link" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                        <span class="sr-only">Next</span>
                    </a>
                </li>
            <?php else : ?>
                <li class="page-item disabled">
                    <span class="page-link">
                        Next
                    </span>
                </li>
            <?php endif ?>
        </ul>
    </nav>
<?php endif ?>